name: Web Tests
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Browser to run tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
  
jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Setup Node.js
      uses: actions/setup-node@v2  # Setup Node.js environment
      with:
        node-version: '14'  # Specify the Node.js version to use
    - name: Debug list file
      run: ls -la   
    - name: Cat package.json
      run: cat package.json  

    - name: Install dependencies
      run: |
        npm i  # Install Node.js dependencies  
        npm ls --depth=0
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install jq
      run: sudo apt-get install -y jq  
    - name: Install ChromeDriver
    
      run: |
        LATEST_JSON=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone.json)

        CHROME_VERSION=$(echo $LATEST_JSON | jq -r '.milestones | to_entries | max_by(.key | tonumber) | .value.version')
        CHROMEDRIVER_VERSION=$(echo $LATEST_JSON | jq -r '.milestones | to_entries | max_by(.key | tonumber) | .value.chromeDriver')
  
        echo "Latest Chrome version: $CHROME_VERSION"
        echo "Latest ChromeDriver version: $CHROMEDRIVER_VERSION"


        # Check if the versions are correctly fetched
        if [ -z "$CHROME_VERSION" ] || [ -z "$CHROMEDRIVER_VERSION" ]; then
           echo "Error: Unable to fetch Chrome or ChromeDriver version."
           exit 1
        fi 

        curl -L -O "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"

        unzip chromedriver_linux64.zip
        chmod +x chromedriver-linux64/chromedriver
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        chromedriver --version    

    - name: Run tests
      run: npm test  # Run the tests using npm