name: Web Tests
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Browser to run tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
  
jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Setup Node.js
      uses: actions/setup-node@v2  # Setup Node.js environment
      with:
        node-version: '14'  # Specify the Node.js version to use
    - name: Debug list file
      run: ls -la   
    - name: Cat package.json
      run: cat package.json  

    - name: Install dependencies
      run: |
        npm i  # Install Node.js dependencies  
        npm ls --depth=0
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install jq
      run: sudo apt-get install -y jq  
    - name: Install ChromeDriver
    
      run: |
       LATEST_JSON=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)

       # Extract the latest stable version details
       CHROME_VERSION=$(echo $LATEST_JSON | jq -r '.channels.Stable.version')
       CHROME_URL=$(echo $LATEST_JSON | jq -r '.channels.Stable.downloads.chrome[] | select(.platform=="linux64").url')
       CHROMEDRIVER_URL=$(echo $LATEST_JSON | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64").url')
  
       echo "Latest Chrome version: $CHROME_VERSION"
       echo "Chrome download URL: $CHROME_URL"
       echo "ChromeDriver download URL: $CHROMEDRIVER_URL"
  
       # Download and install Chrome
       wget -O chrome-linux64.zip "$CHROME_URL"
       unzip chrome-linux64.zip
       sudo mv chrome-linux64 /opt/chrome
       #  sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome
  
       #Download and install ChromeDriver
       wget -O chromedriver-linux64.zip "$CHROMEDRIVER_URL"
       unzip chromedriver-linux64.zip
       sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
       sudo chmod +x /usr/local/bin/chromedriver
  
       # Clean up
       rm chrome-linux64.zip chromedriver-linux64.zip
       rm -rf chromedriver-linux64
  
       # Verify installations
       /opt/chrome/chrome --version
       chromedriver --version
       #Set Chrome binary path as an environment variable
       echo "CHROME_BINARY=/opt/chrome/chrome" >> $GITHUB_ENV     

    - name: Run tests
      run: npm test  # Run the tests using npm